### ISSUE TITLE
Uncaught TypeError: webFrame.registerURLSchemeAsBypassingCSP is not a function

### ISSUE THREAD

**Issue by chiso2468** [landaujs/atom-landau-viewer#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [landau-viewer](https://github.com/landaujs/atom-landau-viewer) package 0.0.3

### Stack Trace

Uncaught TypeError: webFrame.registerURLSchemeAsBypassingCSP is not a function

```
At C:\Users\Chiso\.atom\packages\landau-viewer\lib\landau-viewer-view.js:22

TypeError: webFrame.registerURLSchemeAsBypassingCSP is not a function
    at /packages/landau-viewer/lib/landau-viewer-view.js:22:10)
    at /packages/landau-viewer/lib/landau-viewer-view.js:466:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (/packages/psd-viewer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/landau-viewer/lib/landau-viewer.js:3:23)
    at /packages/landau-viewer/lib/landau-viewer.js:246:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (/packages/psd-viewer/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:736637)
    at requireModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1122229)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3509026)
    at Package.activateConfig (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3498314)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:910238)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2652788)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2643056)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2642879)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2651021
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2653039
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:919695)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:916827
    at r (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:911357)
    at n (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1121552)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1121758)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -1:30.7.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-cwl-viewer 0.3.0 
atom-import-js 1.0.0 
atom-master-sharing 0.1.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-trace-viewer 0.1.0 
atom-wdl-viewer 0.2.1 
clipboard-master 0.9.0 
hey-pane 1.2.0 
Hydrogen 2.14.7 
ide-elixir-elixir-lsp-master 0.0.1-rc1 
js-func-viewer 1.1.4 
jscad-viewer 1.2.0 
json 0.0.0 
landau-viewer 0.0.3 
live-doc-viewer 1.2.0 
map-viewer 0.7.2 
pdfjs-viewer 1.0.0 
php-integrator-symbol-viewer 0.6.4 
plain-simple 1.1.0 
psd-viewer 0.1.0 
rust-doc-viewer 2.6.3 
scroll-through-time 0.3.1 
simple-align 0.2.0 
simple-copy-path 1.0.0 
simple-git 0.2.0 
simple-hello-world 0.3.2 
simple-htmlr 1.1.0 
simple-panes 1.2.0 
teletype 0.13.4 
zentabs 0.8.9 
```

**Comment by hobofan** [comment]
Sorry, I don't think I can be of any help here.

I just started working on Landau again the last days after ~3 years of not taking a look at it. The rewrite is based on the [new branch of jscad](https://github.com/jscad/OpenJSCAD.org/tree/V2/packages), and instead of something that is merely resembling React, it is using react-reconclier to be a proper React renderer. So with those big changes all other packages (development is happening in `landaujs/landau`) under the `landaujs` organization can be considered deprecated, and I'll hopefully soon get around to reflect those changes in the repositories.
